# Site settings
title: Ja50n - go ahead
email: 18675559035@163.com
description: > # Study notes, resource sharing, practical projects, living with the mind. Program 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.ulinkmega.com" # the base hostname & protocol for your site
twitter_username: TINE4359
github_username:  Ja50n
weibo_username: TINE59

# Build settings
markdown: kramdown
# highlighter: rouge
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "page:num"
plugins:
  - jekyll-paginate

port: 4000
